// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("VRFRequestTableV")));
bytes32 constant VRFRequestTableV2TableId = _tableId;

struct VRFRequestTableV2Data {
  address msgSender;
  uint256 nonce;
  uint256 blockNumber;
  uint32 callbackGasLimit;
  uint32 nbWords;
  bytes4 callbackSelector;
}

library VRFRequestTableV2 {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](6);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.UINT256;
    _schema[2] = SchemaType.UINT256;
    _schema[3] = SchemaType.UINT32;
    _schema[4] = SchemaType.UINT32;
    _schema[5] = SchemaType.BYTES4;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](6);
    _fieldNames[0] = "msgSender";
    _fieldNames[1] = "nonce";
    _fieldNames[2] = "blockNumber";
    _fieldNames[3] = "callbackGasLimit";
    _fieldNames[4] = "nbWords";
    _fieldNames[5] = "callbackSelector";
    return ("VRFRequestTableV2", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Emit the ephemeral event using individual values */
  function emitEphemeral(
    bytes32 requestId,
    address msgSender,
    uint256 nonce,
    uint256 blockNumber,
    uint32 callbackGasLimit,
    uint32 nbWords,
    bytes4 callbackSelector
  ) internal {
    bytes memory _data = encode(msgSender, nonce, blockNumber, callbackGasLimit, nbWords, callbackSelector);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.emitEphemeralRecord(_tableId, _keyTuple, _data);
  }

  /** Emit the ephemeral event using individual values (using the specified store) */
  function emitEphemeral(
    IStore _store,
    bytes32 requestId,
    address msgSender,
    uint256 nonce,
    uint256 blockNumber,
    uint32 callbackGasLimit,
    uint32 nbWords,
    bytes4 callbackSelector
  ) internal {
    bytes memory _data = encode(msgSender, nonce, blockNumber, callbackGasLimit, nbWords, callbackSelector);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.emitEphemeralRecord(_tableId, _keyTuple, _data);
  }

  /** Emit the ephemeral event using the data struct */
  function emitEphemeral(bytes32 requestId, VRFRequestTableV2Data memory _table) internal {
    emitEphemeral(
      requestId,
      _table.msgSender,
      _table.nonce,
      _table.blockNumber,
      _table.callbackGasLimit,
      _table.nbWords,
      _table.callbackSelector
    );
  }

  /** Emit the ephemeral event using the data struct (using the specified store) */
  function emitEphemeral(IStore _store, bytes32 requestId, VRFRequestTableV2Data memory _table) internal {
    emitEphemeral(
      _store,
      requestId,
      _table.msgSender,
      _table.nonce,
      _table.blockNumber,
      _table.callbackGasLimit,
      _table.nbWords,
      _table.callbackSelector
    );
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    address msgSender,
    uint256 nonce,
    uint256 blockNumber,
    uint32 callbackGasLimit,
    uint32 nbWords,
    bytes4 callbackSelector
  ) internal view returns (bytes memory) {
    return abi.encodePacked(msgSender, nonce, blockNumber, callbackGasLimit, nbWords, callbackSelector);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 requestId) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));
  }
}
