// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("VRFRequestTableV")));
bytes32 constant VRFRequestTableV2TableId = _tableId;

struct VRFRequestTableV2Data {
  address msgSender;
  uint256 nonce;
  uint256 blockNumber;
  uint32 callbackGasLimit;
  uint32 nbWords;
  bytes4 callbackSelector;
}

library VRFRequestTableV2 {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](6);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.UINT256;
    _schema[2] = SchemaType.UINT256;
    _schema[3] = SchemaType.UINT32;
    _schema[4] = SchemaType.UINT32;
    _schema[5] = SchemaType.BYTES4;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](6);
    _fieldNames[0] = "msgSender";
    _fieldNames[1] = "nonce";
    _fieldNames[2] = "blockNumber";
    _fieldNames[3] = "callbackGasLimit";
    _fieldNames[4] = "nbWords";
    _fieldNames[5] = "callbackSelector";
    return ("VRFRequestTableV2", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get msgSender */
  function getMsgSender(bytes32 requestId) internal view returns (address msgSender) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get msgSender (using the specified store) */
  function getMsgSender(IStore _store, bytes32 requestId) internal view returns (address msgSender) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Set msgSender */
  function setMsgSender(bytes32 requestId, address msgSender) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((msgSender)));
  }

  /** Set msgSender (using the specified store) */
  function setMsgSender(IStore _store, bytes32 requestId, address msgSender) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((msgSender)));
  }

  /** Get nonce */
  function getNonce(bytes32 requestId) internal view returns (uint256 nonce) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get nonce (using the specified store) */
  function getNonce(IStore _store, bytes32 requestId) internal view returns (uint256 nonce) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set nonce */
  function setNonce(bytes32 requestId, uint256 nonce) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((nonce)));
  }

  /** Set nonce (using the specified store) */
  function setNonce(IStore _store, bytes32 requestId, uint256 nonce) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((nonce)));
  }

  /** Get blockNumber */
  function getBlockNumber(bytes32 requestId) internal view returns (uint256 blockNumber) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get blockNumber (using the specified store) */
  function getBlockNumber(IStore _store, bytes32 requestId) internal view returns (uint256 blockNumber) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set blockNumber */
  function setBlockNumber(bytes32 requestId, uint256 blockNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((blockNumber)));
  }

  /** Set blockNumber (using the specified store) */
  function setBlockNumber(IStore _store, bytes32 requestId, uint256 blockNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((blockNumber)));
  }

  /** Get callbackGasLimit */
  function getCallbackGasLimit(bytes32 requestId) internal view returns (uint32 callbackGasLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get callbackGasLimit (using the specified store) */
  function getCallbackGasLimit(IStore _store, bytes32 requestId) internal view returns (uint32 callbackGasLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set callbackGasLimit */
  function setCallbackGasLimit(bytes32 requestId, uint32 callbackGasLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.setField(_tableId, _keyTuple, 3, abi.encodePacked((callbackGasLimit)));
  }

  /** Set callbackGasLimit (using the specified store) */
  function setCallbackGasLimit(IStore _store, bytes32 requestId, uint32 callbackGasLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.setField(_tableId, _keyTuple, 3, abi.encodePacked((callbackGasLimit)));
  }

  /** Get nbWords */
  function getNbWords(bytes32 requestId) internal view returns (uint32 nbWords) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 4);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get nbWords (using the specified store) */
  function getNbWords(IStore _store, bytes32 requestId) internal view returns (uint32 nbWords) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 4);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set nbWords */
  function setNbWords(bytes32 requestId, uint32 nbWords) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.setField(_tableId, _keyTuple, 4, abi.encodePacked((nbWords)));
  }

  /** Set nbWords (using the specified store) */
  function setNbWords(IStore _store, bytes32 requestId, uint32 nbWords) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.setField(_tableId, _keyTuple, 4, abi.encodePacked((nbWords)));
  }

  /** Get callbackSelector */
  function getCallbackSelector(bytes32 requestId) internal view returns (bytes4 callbackSelector) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 5);
    return (Bytes.slice4(_blob, 0));
  }

  /** Get callbackSelector (using the specified store) */
  function getCallbackSelector(IStore _store, bytes32 requestId) internal view returns (bytes4 callbackSelector) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 5);
    return (Bytes.slice4(_blob, 0));
  }

  /** Set callbackSelector */
  function setCallbackSelector(bytes32 requestId, bytes4 callbackSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.setField(_tableId, _keyTuple, 5, abi.encodePacked((callbackSelector)));
  }

  /** Set callbackSelector (using the specified store) */
  function setCallbackSelector(IStore _store, bytes32 requestId, bytes4 callbackSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.setField(_tableId, _keyTuple, 5, abi.encodePacked((callbackSelector)));
  }

  /** Get the full data */
  function get(bytes32 requestId) internal view returns (VRFRequestTableV2Data memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 requestId) internal view returns (VRFRequestTableV2Data memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 requestId,
    address msgSender,
    uint256 nonce,
    uint256 blockNumber,
    uint32 callbackGasLimit,
    uint32 nbWords,
    bytes4 callbackSelector
  ) internal {
    bytes memory _data = encode(msgSender, nonce, blockNumber, callbackGasLimit, nbWords, callbackSelector);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 requestId,
    address msgSender,
    uint256 nonce,
    uint256 blockNumber,
    uint32 callbackGasLimit,
    uint32 nbWords,
    bytes4 callbackSelector
  ) internal {
    bytes memory _data = encode(msgSender, nonce, blockNumber, callbackGasLimit, nbWords, callbackSelector);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 requestId, VRFRequestTableV2Data memory _table) internal {
    set(
      requestId,
      _table.msgSender,
      _table.nonce,
      _table.blockNumber,
      _table.callbackGasLimit,
      _table.nbWords,
      _table.callbackSelector
    );
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 requestId, VRFRequestTableV2Data memory _table) internal {
    set(
      _store,
      requestId,
      _table.msgSender,
      _table.nonce,
      _table.blockNumber,
      _table.callbackGasLimit,
      _table.nbWords,
      _table.callbackSelector
    );
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (VRFRequestTableV2Data memory _table) {
    _table.msgSender = (address(Bytes.slice20(_blob, 0)));

    _table.nonce = (uint256(Bytes.slice32(_blob, 20)));

    _table.blockNumber = (uint256(Bytes.slice32(_blob, 52)));

    _table.callbackGasLimit = (uint32(Bytes.slice4(_blob, 84)));

    _table.nbWords = (uint32(Bytes.slice4(_blob, 88)));

    _table.callbackSelector = (Bytes.slice4(_blob, 92));
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    address msgSender,
    uint256 nonce,
    uint256 blockNumber,
    uint32 callbackGasLimit,
    uint32 nbWords,
    bytes4 callbackSelector
  ) internal view returns (bytes memory) {
    return abi.encodePacked(msgSender, nonce, blockNumber, callbackGasLimit, nbWords, callbackSelector);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 requestId) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 requestId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 requestId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((requestId));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
