/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace VRF {
  export type ProofStruct = {
    pk: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    gamma: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    c: PromiseOrValue<BigNumberish>;
    s: PromiseOrValue<BigNumberish>;
    seed: PromiseOrValue<BigNumberish>;
    uWitness: PromiseOrValue<string>;
    cGammaWitness: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    sHashWitness: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    zInv: PromiseOrValue<BigNumberish>;
  };

  export type ProofStructOutput = [
    [BigNumber, BigNumber],
    [BigNumber, BigNumber],
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    [BigNumber, BigNumber],
    [BigNumber, BigNumber],
    BigNumber
  ] & {
    pk: [BigNumber, BigNumber];
    gamma: [BigNumber, BigNumber];
    c: BigNumber;
    s: BigNumber;
    seed: BigNumber;
    uWitness: string;
    cGammaWitness: [BigNumber, BigNumber];
    sHashWitness: [BigNumber, BigNumber];
    zInv: BigNumber;
  };

  export type RequestStruct = {
    sender: PromiseOrValue<string>;
    blockNumber: PromiseOrValue<BigNumberish>;
    oracleId: PromiseOrValue<BytesLike>;
    requestConfirmations: PromiseOrValue<BigNumberish>;
    callbackGasLimit: PromiseOrValue<BigNumberish>;
    nbWords: PromiseOrValue<BigNumberish>;
    callbackSelector: PromiseOrValue<BytesLike>;
  };

  export type RequestStructOutput = [
    string,
    BigNumber,
    string,
    number,
    number,
    number,
    string
  ] & {
    sender: string;
    blockNumber: BigNumber;
    oracleId: string;
    requestConfirmations: number;
    callbackGasLimit: number;
    nbWords: number;
    callbackSelector: string;
  };
}

export interface IVRFCoordinatorInterface extends utils.Interface {
  functions: {
    "fulfillRandomWords((uint256[2],uint256[2],uint256,uint256,uint256,address,uint256[2],uint256[2],uint256),(address,uint64,bytes32,uint16,uint32,uint32,bytes4))": FunctionFragment;
    "requestRandomWords(bytes32,uint16,uint32,uint32,bytes4)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "fulfillRandomWords" | "requestRandomWords"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "fulfillRandomWords",
    values: [VRF.ProofStruct, VRF.RequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomWords",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "fulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomWords",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IVRFCoordinator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IVRFCoordinatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    fulfillRandomWords(
      _proof: VRF.ProofStruct,
      _request: VRF.RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  fulfillRandomWords(
    _proof: VRF.ProofStruct,
    _request: VRF.RequestStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestRandomWords(
    _oracleId: PromiseOrValue<BytesLike>,
    _requestConfirmations: PromiseOrValue<BigNumberish>,
    _callbackGasLimit: PromiseOrValue<BigNumberish>,
    _nbWords: PromiseOrValue<BigNumberish>,
    _callbackSelector: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    fulfillRandomWords(
      _proof: VRF.ProofStruct,
      _request: VRF.RequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    fulfillRandomWords(
      _proof: VRF.ProofStruct,
      _request: VRF.RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fulfillRandomWords(
      _proof: VRF.ProofStruct,
      _request: VRF.RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
