/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace VRF {
  export type ProofStruct = {
    pk: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    gamma: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    c: PromiseOrValue<BigNumberish>;
    s: PromiseOrValue<BigNumberish>;
    seed: PromiseOrValue<BigNumberish>;
    uWitness: PromiseOrValue<string>;
    cGammaWitness: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    sHashWitness: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>];
    zInv: PromiseOrValue<BigNumberish>;
  };

  export type ProofStructOutput = [
    [BigNumber, BigNumber],
    [BigNumber, BigNumber],
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    [BigNumber, BigNumber],
    [BigNumber, BigNumber],
    BigNumber
  ] & {
    pk: [BigNumber, BigNumber];
    gamma: [BigNumber, BigNumber];
    c: BigNumber;
    s: BigNumber;
    seed: BigNumber;
    uWitness: string;
    cGammaWitness: [BigNumber, BigNumber];
    sHashWitness: [BigNumber, BigNumber];
    zInv: BigNumber;
  };

  export type RequestStruct = {
    sender: PromiseOrValue<string>;
    blockNumber: PromiseOrValue<BigNumberish>;
    oracleId: PromiseOrValue<BytesLike>;
    requestConfirmations: PromiseOrValue<BigNumberish>;
    callbackGasLimit: PromiseOrValue<BigNumberish>;
    nbWords: PromiseOrValue<BigNumberish>;
    callbackSelector: PromiseOrValue<BytesLike>;
  };

  export type RequestStructOutput = [
    string,
    BigNumber,
    string,
    number,
    number,
    number,
    string
  ] & {
    sender: string;
    blockNumber: BigNumber;
    oracleId: string;
    requestConfirmations: number;
    callbackGasLimit: number;
    nbWords: number;
    callbackSelector: string;
  };
}

export interface VRFCoordinatorInterface extends utils.Interface {
  functions: {
    "MAXIMUM_CALLBACK_GAS_LIMIT()": FunctionFragment;
    "MAXIMUM_NB_WORDS()": FunctionFragment;
    "MINIMUM_REQUEST_CONFIRMATIONS()": FunctionFragment;
    "ORACLE_ADDRESS()": FunctionFragment;
    "ORACLE_ID()": FunctionFragment;
    "fulfillRandomWords((uint256[2],uint256[2],uint256,uint256,uint256,address,uint256[2],uint256[2],uint256),(address,uint64,bytes32,uint16,uint32,uint32,bytes4))": FunctionFragment;
    "nonce()": FunctionFragment;
    "oracles(bytes32)": FunctionFragment;
    "requestRandomWords(bytes32,uint16,uint32,uint32,bytes4)": FunctionFragment;
    "requests(bytes32)": FunctionFragment;
    "storageProofOracle()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAXIMUM_CALLBACK_GAS_LIMIT"
      | "MAXIMUM_NB_WORDS"
      | "MINIMUM_REQUEST_CONFIRMATIONS"
      | "ORACLE_ADDRESS"
      | "ORACLE_ID"
      | "fulfillRandomWords"
      | "nonce"
      | "oracles"
      | "requestRandomWords"
      | "requests"
      | "storageProofOracle"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAXIMUM_CALLBACK_GAS_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAXIMUM_NB_WORDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_REQUEST_CONFIRMATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ORACLE_ID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fulfillRandomWords",
    values: [VRF.ProofStruct, VRF.RequestStruct]
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "oracles",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomWords",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "storageProofOracle",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAXIMUM_CALLBACK_GAS_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAXIMUM_NB_WORDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_REQUEST_CONFIRMATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ORACLE_ID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storageProofOracle",
    data: BytesLike
  ): Result;

  events: {
    "FulfillRandomWords(uint256,bytes32,uint256[])": EventFragment;
    "RequestRandomWords(uint256,bytes32,bytes32,uint64)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FulfillRandomWords"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestRandomWords"): EventFragment;
}

export interface FulfillRandomWordsEventObject {
  nonce: BigNumber;
  requestId: string;
  words: BigNumber[];
}
export type FulfillRandomWordsEvent = TypedEvent<
  [BigNumber, string, BigNumber[]],
  FulfillRandomWordsEventObject
>;

export type FulfillRandomWordsEventFilter =
  TypedEventFilter<FulfillRandomWordsEvent>;

export interface RequestRandomWordsEventObject {
  nonce: BigNumber;
  requestId: string;
  seed: string;
  nbWords: BigNumber;
}
export type RequestRandomWordsEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  RequestRandomWordsEventObject
>;

export type RequestRandomWordsEventFilter =
  TypedEventFilter<RequestRandomWordsEvent>;

export interface VRFCoordinator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VRFCoordinatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAXIMUM_CALLBACK_GAS_LIMIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAXIMUM_NB_WORDS(overrides?: CallOverrides): Promise<[BigNumber]>;

    MINIMUM_REQUEST_CONFIRMATIONS(overrides?: CallOverrides): Promise<[number]>;

    ORACLE_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    ORACLE_ID(overrides?: CallOverrides): Promise<[string]>;

    fulfillRandomWords(
      _proof: VRF.ProofStruct,
      _request: VRF.RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    nonce(overrides?: CallOverrides): Promise<[BigNumber]>;

    oracles(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requests(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    storageProofOracle(overrides?: CallOverrides): Promise<[string]>;
  };

  MAXIMUM_CALLBACK_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

  MAXIMUM_NB_WORDS(overrides?: CallOverrides): Promise<BigNumber>;

  MINIMUM_REQUEST_CONFIRMATIONS(overrides?: CallOverrides): Promise<number>;

  ORACLE_ADDRESS(overrides?: CallOverrides): Promise<string>;

  ORACLE_ID(overrides?: CallOverrides): Promise<string>;

  fulfillRandomWords(
    _proof: VRF.ProofStruct,
    _request: VRF.RequestStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  nonce(overrides?: CallOverrides): Promise<BigNumber>;

  oracles(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  requestRandomWords(
    _oracleId: PromiseOrValue<BytesLike>,
    _requestConfirmations: PromiseOrValue<BigNumberish>,
    _callbackGasLimit: PromiseOrValue<BigNumberish>,
    _nbWords: PromiseOrValue<BigNumberish>,
    _callbackSelector: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requests(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  storageProofOracle(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    MAXIMUM_CALLBACK_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    MAXIMUM_NB_WORDS(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_REQUEST_CONFIRMATIONS(overrides?: CallOverrides): Promise<number>;

    ORACLE_ADDRESS(overrides?: CallOverrides): Promise<string>;

    ORACLE_ID(overrides?: CallOverrides): Promise<string>;

    fulfillRandomWords(
      _proof: VRF.ProofStruct,
      _request: VRF.RequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    nonce(overrides?: CallOverrides): Promise<BigNumber>;

    oracles(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    requests(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    storageProofOracle(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "FulfillRandomWords(uint256,bytes32,uint256[])"(
      nonce?: PromiseOrValue<BigNumberish> | null,
      requestId?: PromiseOrValue<BytesLike> | null,
      words?: null
    ): FulfillRandomWordsEventFilter;
    FulfillRandomWords(
      nonce?: PromiseOrValue<BigNumberish> | null,
      requestId?: PromiseOrValue<BytesLike> | null,
      words?: null
    ): FulfillRandomWordsEventFilter;

    "RequestRandomWords(uint256,bytes32,bytes32,uint64)"(
      nonce?: PromiseOrValue<BigNumberish> | null,
      requestId?: PromiseOrValue<BytesLike> | null,
      seed?: null,
      nbWords?: null
    ): RequestRandomWordsEventFilter;
    RequestRandomWords(
      nonce?: PromiseOrValue<BigNumberish> | null,
      requestId?: PromiseOrValue<BytesLike> | null,
      seed?: null,
      nbWords?: null
    ): RequestRandomWordsEventFilter;
  };

  estimateGas: {
    MAXIMUM_CALLBACK_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    MAXIMUM_NB_WORDS(overrides?: CallOverrides): Promise<BigNumber>;

    MINIMUM_REQUEST_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ORACLE_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    ORACLE_ID(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillRandomWords(
      _proof: VRF.ProofStruct,
      _request: VRF.RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    nonce(overrides?: CallOverrides): Promise<BigNumber>;

    oracles(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requests(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    storageProofOracle(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MAXIMUM_CALLBACK_GAS_LIMIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAXIMUM_NB_WORDS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MINIMUM_REQUEST_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ORACLE_ADDRESS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ORACLE_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fulfillRandomWords(
      _proof: VRF.ProofStruct,
      _request: VRF.RequestStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    nonce(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oracles(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requests(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    storageProofOracle(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
