/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface VRFCoordinatorSystemInterface extends utils.Interface {
  functions: {
    "requestRandomWords(bytes32,uint16,uint32,uint32,bytes4)": FunctionFragment;
    "setCoordinator(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "requestRandomWords" | "setCoordinator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "requestRandomWords",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setCoordinator",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "requestRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoordinator",
    data: BytesLike
  ): Result;

  events: {};
}

export interface VRFCoordinatorSystem extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VRFCoordinatorSystemInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setCoordinator(
      _coordinator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  requestRandomWords(
    _oracleId: PromiseOrValue<BytesLike>,
    _requestConfirmations: PromiseOrValue<BigNumberish>,
    _callbackGasLimit: PromiseOrValue<BigNumberish>,
    _nbWords: PromiseOrValue<BigNumberish>,
    _callbackSelector: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setCoordinator(
    _coordinator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    setCoordinator(
      _coordinator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setCoordinator(
      _coordinator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    requestRandomWords(
      _oracleId: PromiseOrValue<BytesLike>,
      _requestConfirmations: PromiseOrValue<BigNumberish>,
      _callbackGasLimit: PromiseOrValue<BigNumberish>,
      _nbWords: PromiseOrValue<BigNumberish>,
      _callbackSelector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setCoordinator(
      _coordinator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
