/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVRFCoordinator,
  IVRFCoordinatorInterface,
} from "../IVRFCoordinator";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256[2]",
            name: "pk",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2]",
            name: "gamma",
            type: "uint256[2]",
          },
          {
            internalType: "uint256",
            name: "c",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "s",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "seed",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "uWitness",
            type: "address",
          },
          {
            internalType: "uint256[2]",
            name: "cGammaWitness",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2]",
            name: "sHashWitness",
            type: "uint256[2]",
          },
          {
            internalType: "uint256",
            name: "zInv",
            type: "uint256",
          },
        ],
        internalType: "struct VRF.Proof",
        name: "_proof",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "blockNumber",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "oracleId",
            type: "bytes32",
          },
          {
            internalType: "uint16",
            name: "requestConfirmations",
            type: "uint16",
          },
          {
            internalType: "uint32",
            name: "callbackGasLimit",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "nbWords",
            type: "uint32",
          },
          {
            internalType: "bytes4",
            name: "callbackSelector",
            type: "bytes4",
          },
        ],
        internalType: "struct VRF.Request",
        name: "_request",
        type: "tuple",
      },
    ],
    name: "fulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_oracleId",
        type: "bytes32",
      },
      {
        internalType: "uint16",
        name: "_requestConfirmations",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "_callbackGasLimit",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_nbWords",
        type: "uint32",
      },
      {
        internalType: "bytes4",
        name: "_callbackSelector",
        type: "bytes4",
      },
    ],
    name: "requestRandomWords",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVRFCoordinator__factory {
  static readonly abi = _abi;
  static createInterface(): IVRFCoordinatorInterface {
    return new utils.Interface(_abi) as IVRFCoordinatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVRFCoordinator {
    return new Contract(address, _abi, signerOrProvider) as IVRFCoordinator;
  }
}
