/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVRFCoordinatorSystem,
  IVRFCoordinatorSystemInterface,
} from "../IVRFCoordinatorSystem";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_oracleId",
        type: "bytes32",
      },
      {
        internalType: "uint16",
        name: "_requestConfirmations",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "_callbackGasLimit",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_nbWords",
        type: "uint32",
      },
      {
        internalType: "bytes4",
        name: "_callbackSelector",
        type: "bytes4",
      },
    ],
    name: "requestRandomWords",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_coordinator",
        type: "address",
      },
    ],
    name: "setCoordinator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVRFCoordinatorSystem__factory {
  static readonly abi = _abi;
  static createInterface(): IVRFCoordinatorSystemInterface {
    return new utils.Interface(_abi) as IVRFCoordinatorSystemInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVRFCoordinatorSystem {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IVRFCoordinatorSystem;
  }
}
