/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { StoreSwitch, StoreSwitchInterface } from "../StoreSwitch";

const _abi = [
  {
    inputs: [],
    name: "StoreSwitch_InvalidInsideConstructor",
    type: "error",
  },
] as const;

export class StoreSwitch__factory {
  static readonly abi = _abi;
  static createInterface(): StoreSwitchInterface {
    return new utils.Interface(_abi) as StoreSwitchInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StoreSwitch {
    return new Contract(address, _abi, signerOrProvider) as StoreSwitch;
  }
}
