/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VRFCoordinator,
  VRFCoordinatorInterface,
} from "../VRFCoordinator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_storageProofOracle",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "FailedToFulfillRandomness",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidCallbackGasLimit",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidCommitment",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidNumberOfWords",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidOracleId",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidRequestConfirmations",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidRequestParameters",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "words",
        type: "uint256[]",
      },
    ],
    name: "FulfillRandomWords",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "seed",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "nbWords",
        type: "uint64",
      },
    ],
    name: "RequestRandomWords",
    type: "event",
  },
  {
    inputs: [],
    name: "MAXIMUM_CALLBACK_GAS_LIMIT",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAXIMUM_NB_WORDS",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MINIMUM_REQUEST_CONFIRMATIONS",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ORACLE_ADDRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ORACLE_ID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256[2]",
            name: "pk",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2]",
            name: "gamma",
            type: "uint256[2]",
          },
          {
            internalType: "uint256",
            name: "c",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "s",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "seed",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "uWitness",
            type: "address",
          },
          {
            internalType: "uint256[2]",
            name: "cGammaWitness",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2]",
            name: "sHashWitness",
            type: "uint256[2]",
          },
          {
            internalType: "uint256",
            name: "zInv",
            type: "uint256",
          },
        ],
        internalType: "struct VRF.Proof",
        name: "_proof",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "blockNumber",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "oracleId",
            type: "bytes32",
          },
          {
            internalType: "uint16",
            name: "requestConfirmations",
            type: "uint16",
          },
          {
            internalType: "uint32",
            name: "callbackGasLimit",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "nbWords",
            type: "uint32",
          },
          {
            internalType: "bytes4",
            name: "callbackSelector",
            type: "bytes4",
          },
        ],
        internalType: "struct VRF.Request",
        name: "_request",
        type: "tuple",
      },
    ],
    name: "fulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nonce",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "oracles",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_oracleId",
        type: "bytes32",
      },
      {
        internalType: "uint16",
        name: "_requestConfirmations",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "_callbackGasLimit",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_nbWords",
        type: "uint32",
      },
      {
        internalType: "bytes4",
        name: "_callbackSelector",
        type: "bytes4",
      },
    ],
    name: "requestRandomWords",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "requests",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "storageProofOracle",
    outputs: [
      {
        internalType: "contract StorageProofOracle",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class VRFCoordinator__factory {
  static readonly abi = _abi;
  static createInterface(): VRFCoordinatorInterface {
    return new utils.Interface(_abi) as VRFCoordinatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VRFCoordinator {
    return new Contract(address, _abi, signerOrProvider) as VRFCoordinator;
  }
}
