// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IVRFCoordinatorSystem {
  function requestRandomWords(
    address _coordinator,
    bytes32 _oracleId,
    uint16 _requestConfirmations,
    uint32 _callbackGasLimit,
    uint32 _nbWords,
    bytes4 _callbackSelector
  ) external returns (bytes32);
}
