// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import {BlackJack, BlackJackData, BlackJackTableId} from "./tables/BlackJack.sol";
import {RequestIdToBlackJackUser, RequestIdToBlackJackUserTableId} from "./tables/RequestIdToBlackJackUser.sol";
import {VRFRequests, VRFRequestsData, VRFRequestsTableId} from "./modules/vrf/tables/VRFRequests.sol";
import {VRFNonce, VRFNonceTableId} from "./modules/vrf/tables/VRFNonce.sol";
