// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { BlackJack, BlackJackData, BlackJackTableId } from "./tables/BlackJack.sol";
import { RequestIdToBlackJackUser, RequestIdToBlackJackUserTableId } from "./tables/RequestIdToBlackJackUser.sol";
