// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { VRFCoordinatorAddress, VRFCoordinatorAddressTableId } from "./modules/vrf/tables/VRFCoordinatorAddress.sol";
