// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { RaffleCounter, RaffleCounterTableId } from "./tables/RaffleCounter.sol";
import { RaffleTable, RaffleTableTableId } from "./tables/RaffleTable.sol";
import { VRFRequestNonce, VRFRequestNonceTableId } from "./tables/VRFRequestNonce.sol";
import { VRFRequestTable, VRFRequestTableTableId } from "./tables/VRFRequestTable.sol";
import { RequestIdToRaffleId, RequestIdToRaffleIdTableId } from "./tables/RequestIdToRaffleId.sol";
import { VRFRequestTableV2, VRFRequestTableV2Data, VRFRequestTableV2TableId } from "./tables/VRFRequestTableV2.sol";
import { BlackJack, BlackJackData, BlackJackTableId } from "./tables/BlackJack.sol";
import { RequestIdToBlackJackUser, RequestIdToBlackJackUserTableId } from "./tables/RequestIdToBlackJackUser.sol";
