/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBlockhashStore,
  IBlockhashStoreInterface,
} from "../IBlockhashStore";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "n",
        type: "uint256",
      },
    ],
    name: "getBlockhash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBlockhashStore__factory {
  static readonly abi = _abi;
  static createInterface(): IBlockhashStoreInterface {
    return new utils.Interface(_abi) as IBlockhashStoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBlockhashStore {
    return new Contract(address, _abi, signerOrProvider) as IBlockhashStore;
  }
}
