/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { SchemaLib, SchemaLibInterface } from "../SchemaLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    name: "SchemaLib_InvalidLength",
    type: "error",
  },
  {
    inputs: [],
    name: "SchemaLib_StaticTypeAfterDynamicType",
    type: "error",
  },
] as const;

export class SchemaLib__factory {
  static readonly abi = _abi;
  static createInterface(): SchemaLibInterface {
    return new utils.Interface(_abi) as SchemaLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SchemaLib {
    return new Contract(address, _abi, signerOrProvider) as SchemaLib;
  }
}
