// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRaffleSystem {
  function startNewRaffle() external returns (uint32);

  function buyTicket(uint32 raffleId) external;

  function endRaffle(uint32 raffleId) external;

  function endRaffleCallback(bytes32 requestId, uint256[] memory randomWords) external returns (uint256);
}
